### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by irmaster** [openware/baseapp#158]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/home/iman2/work/lab/baseapp/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:317:13)
    at /home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:335:12)
    at next (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/iman2/work/lab/baseapp/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:317:13)
    at /home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:335:12)
    at next (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/home/iman2/work/lab/baseapp/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/home/iman2/work/lab/baseapp/node_modules/express/lib/router/layer.js:95:5)

**Comment by dmitriy79** [comment]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at noopServiceWorkerMiddleware (/root/gitsfor/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/root/gitsfor/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/gitsfor/node_modules/express/lib/router/index.js:317:13)
    at /root/gitsfor/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/gitsfor/node_modules/express/lib/router/index.js:335:12)
    at next (/root/gitsfor/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/root/gitsfor/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/root/gitsfor/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/gitsfor/node_modules/express/lib/router/index.js:317:13)
    at /root/gitsfor/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/gitsfor/node_modules/express/lib/router/index.js:335:12)
    at next (/root/gitsfor/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/root/gitsfor/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/root/gitsfor/node_modules/express/lib/router/layer.js:95:5)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at noopServiceWorkerMiddleware (/root/gitsfor/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/root/gitsfor/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/gitsfor/node_modules/express/lib/router/index.js:317:13)
    at /root/gitsfor/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/gitsfor/node_modules/express/lib/router/index.js:335:12)
    at next (/root/gitsfor/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/root/gitsfor/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/root/gitsfor/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/gitsfor/node_modules/express/lib/router/index.js:317:13)
    at /root/gitsfor/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/gitsfor/node_modules/express/lib/router/index.js:335:12)
    at next (/root/gitsfor/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/root/gitsfor/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/root/gitsfor/node_modules/express/lib/router/layer.js:95:5)

**Comment by dmitriy79** [comment]
npm i npm-update-all -g
npm-update-all
npm i browserslist
npm i caniuse-lite
npm update caniuse-lite browserslist

**Comment by akhlopiachyi** [comment]
The issue is in your yarn.lock or node_modules
Check your versions in package.json. Please, be sure, you use the correct ones
